### PR TITLE
Octet1/Octet2 binary format support, hex string output

### PR DESCRIPTION
**Pull request by kuro68k**
We need to process binary PDU messages for our application, and this seems like the simplest way to handle them.

### CODE REVIEW

**Comment by AdhamAwadhi** [comment]
Thank you @kuro68k , You made `GetStringFromBytes`, what about `GetBytesFromString` ?

**Comment by kuro68k** [comment]
We did the absolute minimum required for our application I'm afraid.

I added support for ASCII string decoding. I'm not sure how much sense it makes for binary PDU messages, but since you asked: https://github.com/Primayer/JamaaSMPP/commit/5945221206fe40acdcda06ecfd7dc4d15facc2e4

**Comment by gerann0204** [comment]
Do you have sample code for combining UDH Message/ Concatenated Message in Submit_sm pdu?.

**Comment by AdhamAwadhi** [comment]
Thanks @kuro68k I added code manually cause the last changes I removed `SMPPEncodingUtil.cs` .

**Pull request closed without merging**
